moon:
  ## Global flag to enable resource limits to run Moon on Kubernetes cluster, or to disable to run Moon locally on Minikube.
  enabled:
    resources: true

  # Cannot run as root user
  securityContext:
    runAsUser: 1000

##
## Moon entrypoint.
##
  service:
    annotations:
      # Configure DNS entry
      # external-dns.alpha.kubernetes.io/hostname: moon.k8stest.cloud.westpac.co.nz
      # kubernetes.io/external-dns: managed
    labels: {}
    type: NodePort
    # Static IP assignment in case no ingress available:
      # loadBalancerIP: 10.228.160.132
      # Or:
      # metallb.universe.tf/address-pool: itcrowd-moon-s160-a132

  ##
  ## Moon ui entrypoint, "/wd/hub" if necessary.
  ##
  ingress:
    enabled: false
#     annotations:
#       kubernetes.io/ingress.class: nginx
#     host: example.com
#     tls: []
# #     - secretName: moon-tls
# #       hosts:
# #       - example.com


  ##
  ## Moon configuration.
  ##
  config:
    ##
    ## Kernel capabilities, that will be added to every browser pod.
    ##
    # Remove SYS_ADMIN capability as defined in base values, as this permission is not allowed in Westpac's kubernetes offering
    kernelCaps: []

    ## S3 configuration to upload logs and video files.
    s3:
      ## S3 endpoint, default not set.
      endpoint: http://minio.itcrowd-minio:9000
      ## S3 bucket, default not set.
      bucketName: moon
      ## S3 protocol version, default S3v4, use S3v2 for google storage.
      version: S3v2
      ## Pattern to organize storage files, default $sessionId.
      keyPattern: $sessionId
      ## S3 ACCESS_KEY and SECRET_KEY.
      accessKey: "changeme"
      secretKey: "changeme"

  timeouts:
    ## Browser pod will be deleted after this timeout, if there was no comminication with it.
    sessionTimeout: 1m
    ## Browser pod will wait in queue until resources become awailable.
    sessionAttemptTimeout: 30m

  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: moon-node
                operator: Exists
    
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations:
    - effect: NoSchedule
      key: MoonPods
      operator: Exists

  ##
  ## Browser pod configuration.
  ##
  browser:
    ## Additional annotations to be added to every browser pod.
    #annotations: {}

    ## Additional labels to be added to every browser pod.
    #labels: {}

    ## Global node selector for browser pod.
    nodeSelector:
      moon-node: "true"

    # Global browser container resources, can be overridden in quota.
    resources:
      cpu:
        limits: "1"
        requests: "0.5"
      memory:
        #limits: 1Gi
        limits: 3Gi
        requests: 512Mi

  customQuota:
    browsers:
      safari:
        default: "14.0"
        versions:
          "14.0":
            image: docker.artifactory2.westpac.co.nz/browsers/safari:14.0
            port: "4444"
            path: "/"
            env: [ "HOME=/tmp" ]
            tolerations:
              - effect: NoSchedule
                key: MoonPods
                operator: Exists
          "13.0":
            image: docker.artifactory2.westpac.co.nz/browsers/safari:13.0
            port: "4444"
            path: "/"
            env: [ "HOME=/tmp" ]
            tolerations:
              - effect: NoSchedule
                key: MoonPods
                operator: Exists
      MicrosoftEdge:
        default: "93.0"
        versions:
          "100.0":
            image: docker.artifactory2.westpac.co.nz/browsers/edge:100.0
            port: "4444"
            path: "/"
            env: [ "HOME=/tmp" ]
            tolerations:
              - effect: NoSchedule
                key: MoonPods
                operator: Exists
          "99.0":
            image: docker.artifactory2.westpac.co.nz/browsers/edge:99.0
            port: "4444"
            path: "/"
            env: [ "HOME=/tmp" ]
            tolerations:
              - effect: NoSchedule
                key: MoonPods
                operator: Exists
          "93.0":
            image: docker.artifactory2.westpac.co.nz/browsers/edge:93.0
            port: "4444"
            path: "/"
            env: [ "HOME=/tmp" ]
            tolerations:
              - effect: NoSchedule
                key: MoonPods
                operator: Exists
          "91.0":
            image: docker.artifactory2.westpac.co.nz/browsers/edge:91.0
            port: "4444"
            path: "/"
            env: [ "HOME=/tmp" ]
            tolerations:
              - effect: NoSchedule
                key: MoonPods
                operator: Exists
      firefox:
        default: "90.0"
        versions:
          "90.0":
            image: docker.artifactory2.westpac.co.nz/browsers/firefox:90.0
            port: "4444"
            path: "/wd/hub"
            env: [ "HOME=/tmp" ]
            tolerations:
              - effect: NoSchedule
                key: MoonPods
                operator: Exists        
          "89.0":
            image: docker.artifactory2.westpac.co.nz/browsers/firefox:89.0
            port: "4444"
            path: "/wd/hub"
            env: [ "HOME=/tmp" ]
            tolerations:
              - effect: NoSchedule
                key: MoonPods
                operator: Exists
          "82.0":
            image: docker.artifactory2.westpac.co.nz/browsers/firefox:82.0-1
            port: "4444"
            path: "/wd/hub"
            tolerations:
              - effect: NoSchedule
                key: MoonPods
                operator: Exists
      chrome:
        default: "102.0"
        versions:
          "103.0":
            image: docker.artifactory2.westpac.co.nz/browsers/chrome:103.0.5060.53-1 
            port: "4444"
            env: [ "HOME=/tmp" ]
            tolerations:
              - effect: NoSchedule
                key: MoonPods
                operator: Exists
          "102.0":
            image: docker.artifactory2.westpac.co.nz/browsers/chrome:102.0
            port: "4444"
            env: [ "HOME=/tmp" ]
            tolerations:
              - effect: NoSchedule
                key: MoonPods
                operator: Exists
          "101.0":
            image: docker.artifactory2.westpac.co.nz/browsers/chrome:101.0
            port: "4444"
            env: [ "HOME=/tmp" ]
            tolerations:
              - effect: NoSchedule
                key: MoonPods
                operator: Exists
          "100.0":
            image: docker.artifactory2.westpac.co.nz/browsers/chrome:100.0
            port: "4444"
            env: [ "HOME=/tmp" ]
            tolerations:
              - effect: NoSchedule
                key: MoonPods
                operator: Exists
          "99.0":
            image: docker.artifactory2.westpac.co.nz/browsers/chrome:99.0
            port: "4444"
            env: [ "HOME=/tmp" ]
            tolerations:
              - effect: NoSchedule
                key: MoonPods
                operator: Exists
          "98.0":
            image: docker.artifactory2.westpac.co.nz/browsers/chrome:98.0
            port: "4444"
            env: [ "HOME=/tmp" ]
            tolerations:
              - effect: NoSchedule
                key: MoonPods
                operator: Exists
      android:
        default: "10.0"
        versions:
          "10.0":
            image: "browsers/android:6.0"
            port: "4444"
            path: "/wd/hub"
            tolerations:
              - effect: NoSchedule
                key: MoonPods
                operator: Exists

  # # Override moon guest user
  # guestUser: test

  # ## Enable authentication for moon-ui.
  # ui:
  #   auth:
  #     enabled: true
  
  # # test:1q2w3e
  # htpasswd: |
  #   test:$2y$05$Odl5d2RGYUVg9hCSJlVcWOclq56CdS8JEclVUXgIDevfkSbM/Rdxi
  #   ice:$2y$05$d0zUOTAKgcceGvhH/z3PQeVc0M/IJSRobL1Y0tJS7gLKewoAp8UJq

  # quota:
  #   test:
  #   ice:

  # customQuota:
  #   test:
  #     safari:
  #       ...
  #   ice:
  #     safari:
  #       ...
                
  ## Default free Moon license key for 4 parallel sessions.
  # licenseKey: MG1RSVdpc2Z6YjdQQVZjd2lpei9KMkd1T3dzMTFuL1dlRjVSc3NOMUcxZk9QaUxWa3Q5SnBIakIxa09wWm0vVFJqQ0tsa21xVG1OODVRZnlQbjBjVmRHVWFLampTOFF1a3VLRXRPcEUwbnEySG16QWFQWHRDYTVjMm9jZzZFaUJqeFd5ODE4UFBHZzNCNWpCYXlha3oweFBscFl1RnB0V0U1Q3FwOGl5VDdKTk9abG5aSmlPdnRmZDFvSG1nNnVwVXBLV2E4RmYwWHcreERIR29ZTE1XTldPb1hvT2ZCUnZpcDhPWW05a1FqN0hBWWVOYUtLT1lPWlVJa1dsb1gxdjNOT1htTFpZalhsQ3h1Q3V6NWhiQjIwSjVIY0JTYnZybm9zYm14RXFkSFpQWVBKWUlKTzZvVlBnODhQeFErZ1EyTk5sWG82TC9XeXU3aisrNU0rSEdPcXlOSEdlNGx4Zm1nNVhjMWlnNkN1OCtNSVVYRzNqUllqOUY4ZHdReWpSbFNMNmFpL2dRQnc3TzY0U0lwdVF2d29jYi9kVzFSYWFRVkd3ZXYrOVdING8zRWRrYkVONUhRTmQ2MUxsUnFNdmtKeWVHV21tVlVUZ2dsMDRsTFFLTmZNVG81L2JVakNBMGhNeER5VHNJdmVRRGFMMklvTWpvcFk4VERlK1U2bUJvUDVxNVYrcCtDQVhjbjYxQlRaUVp0bmNqL0JBVkdNOEZ4NW9rWHRYSVAxUkY0a1VCckZVTDFyTWF1VkZqSk5xU1pLT293dUpMTTg2SEZ0Sld0eUlRK3ZZZm1pZU0xM292MnVleDBoRlhRdFkvMkt1dUhhN3dKV2pFT0pqaEVzTjhXSy82ZlFFbi9EQzcrNkw3NzhlbmVVZ2lLZ3VFbjlMMXZMYVZ5VWtQaWc9O2V5SnNhV05sYm5ObFpTSTZJa1JsWm1GMWJIUWlMQ0p3Y205a2RXTjBJam9pVFc5dmJpSXNJbTFoZUZObGMzTnBiMjV6SWpvMGZRPT0=

  # 50 parallel sessions
  # licenseKey: MW4vZ215TEM2TUlUekN3L3R3QnRVZDFkUDkzOEo4b0UzUEVPWXZPdzJiRWF2Q2xzZVJLcUxHY2J2aVhQYWlDQ2t1aEhab0puaWNnczRGbStjR29Ca3ZXY2RHUUxhMFhNMmc2cDZpSDNDL3dtejhSckhaT0RVdWxQd3BZUlBYL1g1a05NVDdFYU40NDVhdmVYS3lyRDQzSGQ4cWRLUnV5U1drVWk5SFFUc2hnZUxlSTRyMUowSzkrZVRQTFB0SFc0djhoS3B2clZYcGVod1ZCcWVWN3JLTTdiZkw3RTJWMHZXbDZoQUlYRklEN2pKWlQ5Yy9JRnhnakRsQ09aZkFmZG1CRXl3bmhHSk01MjFFVFUxTnR0Z3UrS1poSFAzeGhKdHREYTBFaFl1ZlViaHgrTE9uOU1NdEdFb2xSUnBVSkFhUlNIZzBiWk9WRzNDUGE3cStLa20vT2FjdThYTzBtY1J5VVdtTXhrY2ppdmhYa3oraEJyRXJnb0FYRFdxdWxtcHR2Nm5WZlJsajFqbldsSFJHY3pSWnZtT3QzZ3FrNGV0RjIycWdzN3FqMi9nVm53cSs0MVIrckp4VHB6TVBhbzhDTzhiaGo0bmlsUVNnS3djamlORjRLWUIyMDBtVWNLSVVoanphcm96V1JacVpEVlh3ZWFKV0Rzc1lNV05SU2dEWU5hUk81NlV5WXFoQ3oxZ1VMZXVvOEpYZ0tpeTJGTU1neHRUR2NIbmx5dS9HY2V0N21SWis3eUpkaDZjL01ZU21pbU1ranRFblhlN2ZBOWpFQkpwemVxaEIyamozWlpvREhTM1hseFNZVG0rRGJXeGxiK2s1VkdKQ1BDQXA5VXVwOXNiaHNZVVdJQUVRZmlVWVZDYm1jaGFHdTNqM1hPVU9nU0dONW9FYVU9O2V5SnNhV05sYm5ObFpTSTZJbGRsYzNSd1lXTWdUbVYzSUZwbFlXeGhibVFnVEdsdGFYUmxaQ0lzSW5CeWIyUjFZM1FpT2lKTmIyOXVJaXdpYldGNFUyVnpjMmx2Ym5NaU9qVXdMQ0owYnlJNk1UWTFOemMxTmpnd01IMD0=
