# Purpose
# -------
# Set proxy environment variables.
#
# Typically this is required by Tool Installer tasks, as these don't obey the windows proxy settings.
#
# The AzureDevops build servers have been configured not to require proxy authorisation on the bluecoat proxy
# so this does not currently support setting the proxy credentials

parameters:
- name: noProxy # Value of NO_PROXY environment variable, set to "" if not required
  type: string
  default: ".westpac.co.nz,.westpactrust.co.nz"

steps:          
- task: PowerShell@2
  displayName: Configure proxy
  inputs:
    targetType: 'inline'
    script: |
      $proxyurl = "http://swg.inet.westpac.co.nz:8080"

      Write-Host "Setting proxy to ${proxyurl}"

      Write-Host ("##vso[task.setvariable variable=HTTP_PROXY]${proxyurl}")
      Write-Host ("##vso[task.setvariable variable=HTTPS_PROXY]${proxyurl}")
      Write-Host ("##vso[task.setvariable variable=NO_PROXY]${{ parameters.noProxy }}")
  enabled: true