azure_tenant: test
environment_type: Test
squad_name: ICE

dynamics365_url: https://prodsupporttt.crm6.dynamics.com

spn_owners: [
  a806d99d-ab24-4564-861f-7343e3edbabf,  # Andrew Sumner
  e2351405-9746-4768-be5e-3df41491ecf6,  # Eric Regnier
]

# Values to lookup from shared keyvault
fico_datapower_id: uat
docusign_datapower_id: syst
securityops_datapower_id: syst
datapower_id: syst

sbus_sender_spn_name: ""

app_service_plan_sku:
  tier: PremiumV2
  size: P1v2
  capacity: null
  autoscale: true
  autoscale_start_capacity: 1

# servicebus_sku:
#   sku: Premium
#   capacity: 1